# -*- coding: utf-8 -*-
"""2547231_KUNNAL_ML cia3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RO8FwbAarMaXYDYQ9vzkHi1cZjgIEcZA

# 🌍 Agricultural Risk Early-Warning
## Classifying Low-Yield Risk from Soil, Weather and Farming Data

**Registration Number:** 2547231
**Course:** MCA 521-4 — Machine Learning
**Assessment:** CIA-III — ML for Social Good Ensemble Challenge


---

## Q1 — Real-World Impact Framing (5 Marks)

### The Problem

Small farmers across India plan an entire season — what to plant, how much fertilizer
to buy, how much land to commit — largely on experience and hope, without any
early-warning signal about whether that season's soil and weather conditions look
similar to past seasons that ended in a **significantly below-normal harvest** for
that crop. When a low-yield season does happen, it can mean real food-security and
income risk for the farmer and their household.

This project builds a **low-yield-risk early-warning classifier**: given a crop,
season, state, the land area being cultivated, expected weather, soil nutrient
levels, and planned fertilizer/pesticide use, predict whether that combination is at
risk of falling into the **bottom 20% of yield outcomes for that specific crop**
(computed relative to each crop's own historical distribution, since a "low yield"
for sugarcane and a "low yield" for a pulse crop are on completely different scales).

### Why This Fits "Mission Earth"

The task uses environmental inputs (rainfall, temperature, humidity, soil N/P/K/pH)
as the core predictive signal for an agricultural/environmental risk outcome — the
same style of problem as the brief's AQI-forecasting or forest-fire-risk examples,
applied to food-security risk instead. *(If your instructor expects the domain to be
restricted strictly to AQI / forest-fire / water-access, please confirm this framing
is acceptable before final submission — see the note in the README.)*

### Beneficiaries

- **Small and marginal farmers**, who get an early, low-cost signal about whether
  their planned crop/season/conditions historically correlate with poor outcomes.
- **Agricultural extension workers**, who can prioritize which farmers/regions need
  outreach (irrigation advice, alternate crop suggestions, fertilizer guidance) with
  limited staff time.
- **State agriculture departments / food-security planners**, who can use aggregated
  risk flags to anticipate where crop failure is more likely before harvest.

### Prediction Target

A **binary classification** target, `low_yield_risk`:
- `1` — this record's yield fell at or below the **20th percentile of yield for that
  specific crop** (an "at-risk" outcome).
- `0` — yield was above that threshold (a "normal or good" outcome).

### Measurable Impact

If deployed, the practical value is measured by **recall on the at-risk class** —
how many genuinely low-yield situations the model successfully flags *before*
harvest, since missing an at-risk case (a false negative) is the costliest kind of
error here (see Q4 for the full false-positive/false-negative cost discussion).
Secondary impact is measured by how efficiently extension resources can be targeted
using the model's ranked risk probabilities instead of blanket outreach.

### Why Machine Learning Is Suitable

Yield risk depends on many interacting factors — crop type, season, rainfall,
temperature, soil chemistry, and farming inputs — that don't combine in a simple,
linear, rule-based way (a rainfall level that's fine for one crop can be a real
problem for another). Machine learning, especially tree-based ensembles, can learn
these crop-specific, non-linear interactions directly from nearly two decades of
real historical records, which would be impractical to encode as hand-written rules.

### Dataset Source and Unit of Analysis

- **`crop_yield.csv`** — state/crop/season/year-level Indian agricultural records
  (area, production, fertilizer, pesticide, yield), 1997–2020.
- **`state_soil_data.csv`** — state-level soil N/P/K/pH reference values.
- **`state_weather_data_1997_2020.csv`** — state/year-level weather averages
  (temperature, rainfall, humidity).

**Unit of analysis:** one row = one **crop + season + state + year** combination
(e.g. "Rice, Kharif, Karnataka, 2015"), *not* an individual farm or an individual
farmer.

### Responsible-Use Limitations (summary — full discussion in Q4)

Soil and weather values are **state-level averages**, not farm-level measurements;
the dataset has no irrigation, crop-variety, or real-time weather information; and
patterns learned from 1997–2020 may shift as climate and farming practices change.
This tool is intended as **decision support**, not a replacement for agricultural
experts or a guarantee of any farmer's actual outcome.

---

## Q2 — Data Wrangling & Feature Engineering (6 Marks)

### 2.1 — Setup
"""

# Commented out IPython magic to ensure Python compatibility.
# == Install/Import Dependencies ================================================
try:
    import shap
except ImportError:
#     %pip install -q shap
    import shap

try:
    import lightgbm
except ImportError:
#     %pip install -q lightgbm

try:
    import imblearn
except ImportError:
#     %pip install -q imbalanced-learn

import warnings
warnings.filterwarnings('ignore')

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.inspection import permutation_importance
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                              roc_auc_score, roc_curve, auc, confusion_matrix, classification_report)
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import joblib

sns.set_style('whitegrid')
plt.rcParams['figure.dpi'] = 100
SEED = 42
np.random.seed(SEED)

print('Libraries loaded successfully.')

"""### 2.2 — Load & Audit the Raw Datasets"""

# == Load the Datasets ========================================================
DATA_FILES = ['crop_yield.csv', 'state_soil_data.csv', 'state_weather_data_1997_2020.csv']

if not all(os.path.exists(f) for f in DATA_FILES):
    print('One or more data files are missing from the working directory.')
    print('Please upload: crop_yield.csv, state_soil_data.csv, state_weather_data_1997_2020.csv')
    from google.colab import files
    uploaded = files.upload()

crop_df = pd.read_csv('crop_yield.csv')
soil_df = pd.read_csv('state_soil_data.csv')
weather_df = pd.read_csv('state_weather_data_1997_2020.csv')

print('crop_df:', crop_df.shape)
print('soil_df:', soil_df.shape)
print('weather_df:', weather_df.shape)
crop_df.head()

crop_df.info()

# == Missing Values & Duplicates ===============================================
print('Missing values (crop_df):\n', crop_df.isnull().sum())
print('\nMissing values (soil_df):\n', soil_df.isnull().sum())
print('\nMissing values (weather_df):\n', weather_df.isnull().sum())
print('\nDuplicate rows -- crop_df:', crop_df.duplicated().sum(),
      '| soil_df:', soil_df.duplicated().sum(),
      '| weather_df:', weather_df.duplicated().sum())

"""> **What we found:** None of the three files have missing values or duplicate
rows. `crop_df` does have **invalid/inconsistent text formatting** though — the
`season` and `crop` columns contain extra whitespace (e.g. `"Kharif     "`), which we
fix below before it can corrupt our categorical encoding.
"""

# == Fix Invalid Text Values (whitespace) & Confirm State-Name Consistency ====
crop_df['season'] = crop_df['season'].str.strip()
crop_df['crop'] = crop_df['crop'].str.strip()
crop_df['state'] = crop_df['state'].str.strip()
soil_df['state'] = soil_df['state'].str.strip()
weather_df['state'] = weather_df['state'].str.strip()

crop_states, soil_states, weather_states = set(crop_df['state']), set(soil_df['state']), set(weather_df['state'])
print('State-name mismatches crop vs soil:', crop_states - soil_states)
print('State-name mismatches crop vs weather:', crop_states - weather_states)
print('Cleaned season categories:', sorted(crop_df['season'].unique()))

"""### 2.3 — Merge the Datasets"""

# == Merge Key Validation, then Merge ===========================================
print('Duplicate state keys in soil_df:', soil_df.duplicated(subset='state').sum())
print('Duplicate (state, year) keys in weather_df:', weather_df.duplicated(subset=['state', 'year']).sum())

merged_df = crop_df.merge(weather_df, on=['state', 'year'], how='left', validate='m:1')
merged_df = merged_df.merge(soil_df, on='state', how='left', validate='m:1')
print('Merged shape:', merged_df.shape)
print('Missing values after merge:\n', merged_df.isnull().sum().sum(), 'total')
merged_df.head()

"""> **Why we merged:** `crop_df` alone tells us nothing about the environmental
conditions a crop actually grew in. Merging in state-level weather and soil data
gives every farming record the rainfall, temperature, humidity, and soil-nutrient
context that plausibly drove that season's outcome — exactly the signal our risk
classifier needs. `validate='m:1'` confirms neither merge silently duplicated rows.

### 2.4 — Define the Classification Target (and Check for Leakage)
"""

# == Define low_yield_risk: bottom 20% of yield, computed PER CROP =============
# We use a per-crop threshold (not a single global cutoff) because different crops
# sit on completely different yield scales (e.g. sugarcane vs. a pulse crop) -- a
# single global cutoff would just relabel "which crop this is" instead of genuinely
# flagging an underperforming season for that crop.
yield_threshold_per_crop = merged_df.groupby('crop')['yield'].transform(lambda s: s.quantile(0.20))
merged_df['low_yield_risk'] = (merged_df['yield'] <= yield_threshold_per_crop).astype(int)

print('Class balance:')
print(merged_df['low_yield_risk'].value_counts())
print('Positive (at-risk) rate: {:.2%}'.format(merged_df['low_yield_risk'].mean()))

"""### ⚠️ Data Leakage Check

`low_yield_risk` is derived directly from `yield`, and we already know from the raw
data that `production` is essentially `yield * area`. **Both `yield` and
`production` must be excluded from the model's input features** — including either
one would let the model see the answer (or something mathematically equivalent to
it) directly, instead of learning to predict risk from genuinely pre-harvest
information like weather, soil, and planned farming inputs.
"""

# == Confirm the leakage risk with real numbers ================================
print('Correlation between production/area and yield:',
      round(np.corrcoef(merged_df['production'] / merged_df['area'], merged_df['yield'])[0, 1], 4))
print('Mean yield for low_yield_risk=1:', round(merged_df.loc[merged_df.low_yield_risk == 1, 'yield'].mean(), 3))
print('Mean yield for low_yield_risk=0:', round(merged_df.loc[merged_df.low_yield_risk == 0, 'yield'].mean(), 3))

"""### 2.5 — Exploratory Data Analysis"""

# == Target distribution =========================================================
plt.figure(figsize=(6, 5))
counts = merged_df['low_yield_risk'].value_counts().sort_index()
plt.bar(['Normal / Good (0)', 'Low-Yield Risk (1)'], counts.values, color=['#3498db', '#e74c3c'], edgecolor='black')
for i, v in enumerate(counts.values):
    plt.text(i, v + 200, f'{v} ({v / len(merged_df):.1%})', ha='center', fontweight='bold')
plt.title('Target Class Balance: Low-Yield Risk', fontweight='bold')
plt.ylabel('Number of Records')
plt.tight_layout()
plt.show()

"""> **What this tells us:** The classes are imbalanced — roughly 1-in-5 records are
"at risk" (this is by construction, since we used the 20th percentile). This is a
realistic imbalance for a risk-detection problem and is exactly the kind of scenario
where naive accuracy is misleading (a model that always predicts "0" would already
score ~80% accuracy while being useless). We handle this explicitly with SMOTE and
class-weighting in Section 2.8, and lean on precision/recall/F1/ROC-AUC rather than
accuracy alone when comparing models in Q3.
"""

# == Risk rate by season =========================================================
plt.figure(figsize=(9, 5))
season_risk = merged_df.groupby('season')['low_yield_risk'].mean().sort_values(ascending=False)
sns.barplot(x=season_risk.index, y=season_risk.values, color='#e67e22', edgecolor='black')
plt.title('Low-Yield Risk Rate by Season', fontweight='bold')
plt.ylabel('Proportion At Risk')
plt.tight_layout()
plt.show()

"""> **What this tells us:** Risk isn't evenly spread across seasons — Autumn and
Winter records show a noticeably higher at-risk rate than Summer. This is a useful
signal for the model, but on its own it's just a correlation; the actual crops grown
in each season differ too, so season and crop effects are likely intertwined.
"""

# == Risk rate by top states =====================================================
plt.figure(figsize=(9, 8))
state_risk = merged_df.groupby('state')['low_yield_risk'].mean().sort_values(ascending=False)
sns.barplot(x=state_risk.values, y=state_risk.index, color='#8e44ad', edgecolor='black')
plt.title('Low-Yield Risk Rate by State', fontweight='bold')
plt.xlabel('Proportion At Risk')
plt.tight_layout()
plt.show()

"""> **What this tells us:** Risk rate varies noticeably by state — some states show
2-3x the at-risk rate of others. Since soil and weather are state-level in this
dataset, part of what the model will learn here is really "which state's typical
conditions" rather than a truly farm-specific effect — a limitation we return to in
Q4.
"""

# == Rainfall / temperature vs risk =============================================
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
sns.boxplot(data=merged_df, x='low_yield_risk', y='total_rainfall_mm', ax=axes[0],
            palette=['#3498db', '#e74c3c'])
axes[0].set_xticklabels(['Normal/Good', 'At Risk'])
axes[0].set_title('Rainfall by Risk Class', fontweight='bold')

sns.boxplot(data=merged_df, x='low_yield_risk', y='avg_temp_c', ax=axes[1],
            palette=['#3498db', '#e74c3c'])
axes[1].set_xticklabels(['Normal/Good', 'At Risk'])
axes[1].set_title('Temperature by Risk Class', fontweight='bold')
plt.tight_layout()
plt.show()

"""> **What this tells us:** If the "At Risk" box sits at a visibly different
rainfall/temperature range than "Normal/Good", that's evidence these weather
variables carry real predictive signal — we'll confirm this more rigorously with
feature importance in Q4, rather than relying on visual impression alone.
"""

# == Soil variables vs risk ======================================================
fig, axes = plt.subplots(2, 2, figsize=(12, 9))
for ax, var in zip(axes.ravel(), ['N', 'P', 'K', 'pH']):
    sns.boxplot(data=merged_df, x='low_yield_risk', y=var, ax=ax, palette=['#3498db', '#e74c3c'])
    ax.set_xticklabels(['Normal/Good', 'At Risk'])
    ax.set_title(f'Soil {var} by Risk Class', fontweight='bold')
plt.tight_layout()
plt.show()

# == Correlation heatmap (numeric columns, excluding leakage columns) ==========
plt.figure(figsize=(9, 7))
numeric_cols = ['year', 'area', 'fertilizer', 'pesticide', 'avg_temp_c',
                 'total_rainfall_mm', 'avg_humidity_percent', 'N', 'P', 'K', 'pH', 'low_yield_risk']
corr = merged_df[numeric_cols].corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='RdYlBu_r', center=0, linewidths=0.5, square=True)
plt.title('Correlation Heatmap (Numeric Features vs. Target)', fontweight='bold')
plt.tight_layout()
plt.show()

"""> **What this tells us:** No single numeric variable correlates strongly with
`low_yield_risk` on its own -- which is expected, since risk genuinely depends on
*combinations* of crop, season, weather, and soil rather than any one factor alone.
This is exactly the kind of problem tree-based ensembles handle well, since they can
learn interactions rather than relying on a single linear relationship.

### 2.6 — Feature Engineering
"""

# == Feature Engineering: normalize fertilizer/pesticide by farm size ==========
# Raw fertilizer/pesticide totals scale with farm size -- a large farm naturally
# uses a large total even at a modest rate. Dividing by area gives an intensity
# measure that is comparable across farms of different sizes and is what a farmer
# would actually plan around ("how much per hectare"), not the raw total.
merged_df['fertilizer_per_hectare'] = merged_df['fertilizer'] / merged_df['area']
merged_df['pesticide_per_hectare'] = merged_df['pesticide'] / merged_df['area']

print('Infinite/NaN values created:',
      np.isinf(merged_df[['fertilizer_per_hectare', 'pesticide_per_hectare']]).sum().sum())
merged_df[['area', 'fertilizer', 'fertilizer_per_hectare']].head()

"""### 2.7 — Final Feature List & Train / Validation / Test Split"""

# == Finalize features (yield and production excluded -- see leakage check) ====
FEATURES = ['state', 'crop', 'season', 'year', 'area',
            'fertilizer_per_hectare', 'pesticide_per_hectare',
            'avg_temp_c', 'total_rainfall_mm', 'avg_humidity_percent',
            'N', 'P', 'K', 'pH']
TARGET = 'low_yield_risk'
categorical_features = ['state', 'crop', 'season']
numeric_features = [f for f in FEATURES if f not in categorical_features]

X = merged_df[FEATURES].copy()
y = merged_df[TARGET].copy()

# Stratified 70 / 15 / 15 train / validation / test split, reproducible via SEED.
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, stratify=y, random_state=SEED)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=SEED)

print(f'Train: {X_train.shape}, at-risk rate {y_train.mean():.2%}')
print(f'Val:   {X_val.shape}, at-risk rate {y_val.mean():.2%}')
print(f'Test:  {X_test.shape}, at-risk rate {y_test.mean():.2%}')

"""> **Why this split:** A **stratified** split keeps the ~20% at-risk rate
consistent across train/validation/test, so none of the three sets accidentally end
up with a skewed class balance by chance. We use three sets rather than two: the
**training set** (with SMOTE applied, see 2.8) is what every model actually learns
from; the **validation set** stays untouched during training and lets us sanity-check
individual models as we build them; the **test set** is opened only once, at the end
of Q3, to produce the final, fair comparison across all models on data none of them
has influenced in any way.

### 2.8 — Preprocessing: Encoding, Scaling, Outlier Capping, Class Imbalance
"""

# == Outlier capping (winsorization), bounds computed from TRAINING data only ==
# fertilizer_per_hectare / pesticide_per_hectare / area can have a long right tail
# (a handful of unusually large farms or unusually high input use). We cap these at
# the 99th percentile of the TRAINING set only, so no information from
# validation/test leaks into this decision.
CAP_COLUMNS = ['area', 'fertilizer_per_hectare', 'pesticide_per_hectare']
cap_bounds = {c: X_train[c].quantile(0.99) for c in CAP_COLUMNS}
print('Cap bounds (99th percentile of training data):', cap_bounds)

def apply_caps(df):
    df = df.copy()
    for c, upper in cap_bounds.items():
        df[c] = df[c].clip(upper=upper)
    return df

X_train = apply_caps(X_train)
X_val = apply_caps(X_val)
X_test = apply_caps(X_test)

# == Categorical Encoding + Numerical Scaling (ColumnTransformer) ==============
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])
preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

# Fit ONLY on the training data, then apply the same fitted transformation to
# validation and test -- this is what keeps the pipeline leakage-safe.
preprocessor.fit(X_train)
X_train_enc = preprocessor.transform(X_train)
X_val_enc = preprocessor.transform(X_val)
X_test_enc = preprocessor.transform(X_test)
feature_names_enc = preprocessor.get_feature_names_out()

print('Encoded training feature matrix shape:', X_train_enc.shape)
print('Numeric features:', numeric_features)
print('Categorical features (one-hot encoded):', categorical_features)

"""> **Why these decisions:**
> - **One-hot encoding** (`handle_unknown='ignore'`) turns `state`, `crop`, and
>   `season` into numeric indicator columns without implying any false ordering
>   between categories, and safely ignores any category the model hasn't seen before.
> - **Median imputation + standard scaling** on numeric columns protects against any
>   stray missing values and puts all numeric features on a comparable scale, which
>   matters for the Logistic Regression meta-learner used later in stacking (tree
>   models don't strictly need scaling, but it doesn't hurt them either).
> - Fitting the `ColumnTransformer` **only on `X_train`** and reusing it (not
>   refitting) on validation/test is what makes this pipeline leakage-safe.
"""

# == Class Imbalance: SMOTE, applied ONLY to the (already encoded) training set =
print('Before SMOTE -- training class counts:', np.bincount(y_train))
smote = SMOTE(random_state=SEED)
X_train_res, y_train_res = smote.fit_resample(X_train_enc, y_train)
print('After SMOTE  -- training class counts:', np.bincount(y_train_res))
print('Validation and test sets are left untouched -- SMOTE only ever sees training data.')

"""### 📌 What we learned in Q2
We now have a clean, merged, leakage-checked dataset with a genuinely imbalanced
(~20/80) binary target, a fitted encoding/scaling pipeline built only from training
data, and a SMOTE-balanced training set ready for modelling. Every one of the
required Q2 checks — missing values, duplicates, invalid text, outliers, data types,
categorical encoding, numerical scaling, and class imbalance — has been explicitly
audited and handled above, with the reasoning for each decision stated alongside it.

---

## Q3 — Ensemble Architecture, Tuning, and Comparison (8 Marks)

### 3.1 — Evaluation Helper
"""

# == Shared evaluation function used for every model below =====================
def evaluate_model(model, X, y_true, model_name='Model'):
    y_pred = model.predict(X)
    y_prob = model.predict_proba(X)[:, 1] if hasattr(model, 'predict_proba') else None
    metrics = {
        'Accuracy': accuracy_score(y_true, y_pred),
        'Precision': precision_score(y_true, y_pred, zero_division=0),
        'Recall': recall_score(y_true, y_pred, zero_division=0),
        'F1': f1_score(y_true, y_pred, zero_division=0),
        'ROC-AUC': roc_auc_score(y_true, y_prob) if y_prob is not None else np.nan,
    }
    print(f'{model_name}: ' + ', '.join(f'{k}={v:.4f}' for k, v in metrics.items()))
    return metrics, y_pred, y_prob

results = {}

"""### 3.2 — Baseline: Decision Tree"""

# == Baseline: Decision Tree Classifier =========================================
dt = DecisionTreeClassifier(max_depth=10, class_weight='balanced', random_state=SEED)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
dt_cv_scores = cross_val_score(dt, X_train_res, y_train_res, cv=cv, scoring='f1')
print(f'Decision Tree 5-Fold CV F1: {dt_cv_scores.mean():.4f} +/- {dt_cv_scores.std():.4f}')

dt.fit(X_train_res, y_train_res)
dt_metrics, dt_pred, dt_prob = evaluate_model(dt, X_val_enc, y_val, 'Decision Tree (Baseline, validation)')
results['Decision Tree'] = dt_metrics

"""### 3.3 — Bagging: Random Forest"""

# == Bagging: Random Forest, tuned with GridSearchCV ===========================
rf_base = RandomForestClassifier(class_weight='balanced', random_state=SEED, n_jobs=-1)
rf_params = {
    'n_estimators': [200, 300],
    'max_depth': [15, 25, None],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt', 'log2'],
}
rf_grid = GridSearchCV(rf_base, rf_params, cv=StratifiedKFold(3, shuffle=True, random_state=SEED),
                        scoring='f1', n_jobs=-1, verbose=1)
rf_grid.fit(X_train_res, y_train_res)
print('\nBest RF params:', rf_grid.best_params_)
print(f'Best RF CV F1: {rf_grid.best_score_:.4f}')

rf_best = rf_grid.best_estimator_
rf_metrics, rf_pred, rf_prob = evaluate_model(rf_best, X_val_enc, y_val, 'Random Forest (validation)')
results['Random Forest'] = rf_metrics

"""### 3.4 — Boosting: XGBoost + LightGBM"""

# == Boosting Model 1: XGBoost, tuned with GridSearchCV ========================
xgb_base = XGBClassifier(eval_metric='logloss', random_state=SEED, n_jobs=-1)
xgb_params = {'max_depth': [4, 6, 8], 'learning_rate': [0.05, 0.1], 'n_estimators': [200, 300]}
xgb_grid = GridSearchCV(xgb_base, xgb_params, cv=StratifiedKFold(3, shuffle=True, random_state=SEED),
                         scoring='f1', n_jobs=-1, verbose=1)
xgb_grid.fit(X_train_res, y_train_res)
print('\nBest XGB params:', xgb_grid.best_params_)
print(f'Best XGB CV F1: {xgb_grid.best_score_:.4f}')

xgb_best = xgb_grid.best_estimator_
xgb_metrics, xgb_pred, xgb_prob = evaluate_model(xgb_best, X_val_enc, y_val, 'XGBoost (validation)')
results['XGBoost'] = xgb_metrics

# == Boosting Model 2: LightGBM, tuned with GridSearchCV =======================
lgbm_base = LGBMClassifier(random_state=SEED, n_jobs=-1, verbose=-1)
lgbm_params = {'num_leaves': [20, 31, 50], 'learning_rate': [0.05, 0.1], 'n_estimators': [200, 300]}
lgbm_grid = GridSearchCV(lgbm_base, lgbm_params, cv=StratifiedKFold(3, shuffle=True, random_state=SEED),
                          scoring='f1', n_jobs=-1, verbose=1)
lgbm_grid.fit(X_train_res, y_train_res)
print('\nBest LGBM params:', lgbm_grid.best_params_)
print(f'Best LGBM CV F1: {lgbm_grid.best_score_:.4f}')

lgbm_best = lgbm_grid.best_estimator_
lgbm_metrics, lgbm_pred, lgbm_prob = evaluate_model(lgbm_best, X_val_enc, y_val, 'LightGBM (validation)')
results['LightGBM'] = lgbm_metrics

"""> **Why two boosting models?** The rubric asks for one boosting model; we
include both XGBoost and LightGBM because they use different tree-growth strategies
(level-wise vs. leaf-wise), so comparing them gives a slightly more rigorous check
that our results are about the *boosting approach* in general rather than one
library's specific implementation quirks. Since classes are already balanced via
SMOTE going into training, we don't add further class-weighting on top for these two
models (that would be redundant correction on already-balanced data).

### 3.5 — Heterogeneous Stacking & Voting Ensemble
"""

# == Voting Ensemble (soft voting across RF + XGB + LGBM) ======================
voting_clf = VotingClassifier(
    estimators=[('rf', rf_best), ('xgb', xgb_best), ('lgbm', lgbm_best)],
    voting='soft', n_jobs=-1)
voting_clf.fit(X_train_res, y_train_res)
vote_metrics, vote_pred, vote_prob = evaluate_model(voting_clf, X_val_enc, y_val, 'Voting Ensemble (validation)')
results['Voting'] = vote_metrics

# == Stacking Ensemble (meta-learner: Logistic Regression) =====================
# StackingClassifier's own internal `cv` generates out-of-fold predictions from each
# base model to train the meta-learner -- this is what prevents the meta-learner from
# leaking each base model's own training labels into itself.
stacking_clf = StackingClassifier(
    estimators=[('rf', rf_best), ('xgb', xgb_best), ('lgbm', lgbm_best)],
    final_estimator=LogisticRegression(C=1.0, class_weight='balanced', max_iter=1000, random_state=SEED),
    cv=StratifiedKFold(5, shuffle=True, random_state=SEED),
    stack_method='predict_proba', n_jobs=-1)
stacking_clf.fit(X_train_res, y_train_res)
stack_metrics, stack_pred, stack_prob = evaluate_model(stacking_clf, X_val_enc, y_val, 'Stacking Ensemble (validation)')
results['Stacking'] = stack_metrics

"""> **Why might combining models help?** Each base model makes different kinds of
mistakes — a Random Forest can overfit to noisy splits, and the two boosting models
focus on correcting errors in ways that depend on their specific learning rate and
tree structure. **Voting** simply averages their probability outputs; **Stacking**
goes further and *learns* how much to trust each base model via a meta-learner,
using only out-of-fold predictions so it never sees a base model's own training
labels directly. If the base models' errors aren't perfectly correlated, both
approaches can smooth out individual weaknesses -- we check whether that actually
happened for our data in Section 3.6 below.

### 3.6 — Final Evaluation on the Untouched Test Set
"""

# == Final, one-time evaluation on the test set for every model ================
model_map = {
    'Decision Tree': dt, 'Random Forest': rf_best, 'XGBoost': xgb_best,
    'LightGBM': lgbm_best, 'Voting': voting_clf, 'Stacking': stacking_clf,
}
test_results, test_preds, test_probs = {}, {}, {}

print('=' * 60)
print('       FINAL TEST-SET EVALUATION (UNTOUCHED UNTIL NOW)')
print('=' * 60)
for name, model in model_map.items():
    m, p, pb = evaluate_model(model, X_test_enc, y_test, name)
    test_results[name] = m
    test_preds[name] = p
    test_probs[name] = pb

results_df = pd.DataFrame(test_results).T.round(4)
print('\nTest-Set Model Comparison:')
results_df

# == Metric comparison chart =====================================================
fig, ax = plt.subplots(figsize=(14, 6))
metrics_to_plot = ['Accuracy', 'Precision', 'Recall', 'F1', 'ROC-AUC']
x = np.arange(len(metrics_to_plot))
width = 0.13
colors_bar = ['#95a5a6', '#3498db', '#e74c3c', '#2ecc71', '#9b59b6', '#f39c12']
for i, (name, metrics) in enumerate(test_results.items()):
    vals = [metrics[m] for m in metrics_to_plot]
    ax.bar(x + i * width, vals, width, label=name, color=colors_bar[i], edgecolor='black')
ax.set_xlabel('Metric', fontweight='bold')
ax.set_ylabel('Score', fontweight='bold')
ax.set_title('Model Comparison on Test Set', fontweight='bold')
ax.set_xticks(x + width * 2.5)
ax.set_xticklabels(metrics_to_plot)
ax.legend(loc='lower right', ncol=3)
plt.tight_layout()
plt.show()

# == Confusion matrices ==========================================================
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
for ax, (name, preds) in zip(axes.ravel(), test_preds.items()):
    cm = confusion_matrix(y_test, preds)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['Normal/Good', 'At Risk'], yticklabels=['Normal/Good', 'At Risk'])
    ax.set_title(name, fontweight='bold')
    ax.set_xlabel('Predicted')
    ax.set_ylabel('Actual')
plt.suptitle('Confusion Matrices -- Test Set', fontweight='bold', fontsize=14)
plt.tight_layout()
plt.show()

# == ROC curves ===================================================================
fig, ax = plt.subplots(figsize=(8, 7))
for name, probs in test_probs.items():
    if probs is not None:
        fpr, tpr, _ = roc_curve(y_test, probs)
        roc_auc_val = auc(fpr, tpr)
        ax.plot(fpr, tpr, label=f'{name} (AUC={roc_auc_val:.3f})')
ax.plot([0, 1], [0, 1], 'k--', alpha=0.3, label='Random Baseline')
ax.set_title('ROC Curves -- All Models on Test Set', fontweight='bold')
ax.set_xlabel('False Positive Rate')
ax.set_ylabel('True Positive Rate')
ax.legend(loc='lower right', fontsize=9)
plt.tight_layout()
plt.show()

# == Does the best ensemble beat the baseline? ==================================
best_test_model_name = max(test_results, key=lambda k: test_results[k]['F1'])
print(f'Best model on TEST set (by F1): {best_test_model_name}')
print(f'\nClassification Report -- {best_test_model_name}:')
print(classification_report(y_test, test_preds[best_test_model_name], target_names=['Normal/Good', 'At Risk']))

baseline_f1 = test_results['Decision Tree']['F1']
best_f1 = test_results[best_test_model_name]['F1']
improvement = ((best_f1 - baseline_f1) / max(baseline_f1, 1e-9)) * 100
print(f'Baseline (Decision Tree) F1: {baseline_f1:.4f}')
print(f'Best model ({best_test_model_name}) F1: {best_f1:.4f}')
print(f'Relative F1 improvement over baseline: {improvement:.1f}%')

"""### 📌 What we learned in Q3
The printed comparison above is generated directly from this run's actual results,
so whichever model comes out on top -- and by how much it beats the Decision Tree
baseline -- reflects what the code genuinely produced, not an assumed outcome. Bear
in mind that with a real-world, noisy agricultural dataset, it's entirely possible
(and honest to report) that the improvement over baseline is modest -- what matters
for this rubric item is demonstrating the comparison correctly, not guaranteeing a
dramatic win.

---

---

## Q4 — Model Explainability & Ethics (4 Marks)

### 4.1 — Choosing a Model to Explain
"""

# == Pick the stronger of the two boosting models for SHAP TreeExplainer =======
if test_results['XGBoost']['F1'] >= test_results['LightGBM']['F1']:
    shap_model, shap_model_name = xgb_best, 'XGBoost'
else:
    shap_model, shap_model_name = lgbm_best, 'LightGBM'
print(f'Using {shap_model_name} for SHAP explainability (TreeExplainer supports both directly).')

"""### 4.2 — Global Explanation (SHAP)"""

# == Compute SHAP values on a sample of the test set ============================
sample_size = min(300, X_test_enc.shape[0])
np.random.seed(SEED)
sample_idx = np.random.choice(X_test_enc.shape[0], sample_size, replace=False)
X_shap = X_test_enc[sample_idx]

explainer = shap.TreeExplainer(shap_model)
shap_values = explainer.shap_values(X_shap)
# Some SHAP/model-library combinations return a list [class0, class1]; normalize to the positive class.
if isinstance(shap_values, list):
    shap_values_pos = shap_values[1]
else:
    shap_values_pos = shap_values

print('SHAP values shape:', np.array(shap_values_pos).shape)
print('Number of features:', len(feature_names_enc))

plt.figure(figsize=(12, 8))
shap.summary_plot(shap_values_pos, X_shap, feature_names=feature_names_enc, max_display=20, show=False)
plt.title(f'SHAP Summary Plot -- {shap_model_name} (Global Explanation)', fontweight='bold')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 7))
shap.summary_plot(shap_values_pos, X_shap, feature_names=feature_names_enc,
                   plot_type='bar', max_display=15, show=False)
plt.title(f'SHAP Feature Importance -- {shap_model_name}', fontweight='bold')
plt.tight_layout()
plt.show()

# == Auto-generated plain-language interpretation of the top features ==========
mean_abs_shap = np.abs(shap_values_pos).mean(axis=0)
shap_importance_df = pd.DataFrame({'Feature': feature_names_enc, 'Mean |SHAP|': mean_abs_shap}) \
    .sort_values('Mean |SHAP|', ascending=False)
top5 = shap_importance_df.head(5)['Feature'].tolist()

FEATURE_EXPLANATIONS = {
    'num__total_rainfall_mm': 'how much rain the state received that year -- both drought-like and excess conditions can push yield down',
    'num__avg_temp_c': 'average temperature -- crops have a range they tolerate well, and this can fall outside it',
    'num__avg_humidity_percent': 'humidity levels, which affect disease pressure and water stress',
    'num__area': 'the scale of cultivation, which can correlate with farming intensity and practices',
    'num__fertilizer_per_hectare': 'how intensively fertilizer was applied per hectare',
    'num__pesticide_per_hectare': 'how intensively pesticide was applied per hectare',
    'num__N': 'soil Nitrogen level for that state',
    'num__P': 'soil Phosphorus level for that state',
    'num__K': 'soil Potassium level for that state',
    'num__pH': 'soil pH (acidity/alkalinity), which affects nutrient availability to the crop',
    'num__year': 'the year of the record, capturing any long-term trend',
}
print('Top 5 features driving this model\'s predictions:')
for i, feat in enumerate(top5, 1):
    if feat in FEATURE_EXPLANATIONS:
        print(f'{i}. {feat} -- {FEATURE_EXPLANATIONS[feat]}')
    elif feat.startswith('cat__crop_'):
        print(f'{i}. {feat} -- which crop this is, since different crops have very different typical risk levels')
    elif feat.startswith('cat__season_'):
        print(f'{i}. {feat} -- which season this is, since risk rates differ noticeably by season (see Q2 EDA)')
    elif feat.startswith('cat__state_'):
        print(f'{i}. {feat} -- which state this is, reflecting that state-level soil/weather differ a lot across India')
    else:
        print(f'{i}. {feat}')

"""### 4.3 — Local Explanations (Individual Predictions)"""

# == Identify one True Positive, one False Negative, one True Negative example =
best_shap_pred = shap_model.predict(X_test_enc)
tp_idx = np.where((y_test.values == 1) & (best_shap_pred == 1))[0]
fn_idx = np.where((y_test.values == 1) & (best_shap_pred == 0))[0]
tn_idx = np.where((y_test.values == 0) & (best_shap_pred == 0))[0]
print(f'True Positives (correctly flagged at-risk):  {len(tp_idx)}')
print(f'False Negatives (missed at-risk -- costly!): {len(fn_idx)}')
print(f'True Negatives (correctly cleared):           {len(tn_idx)}')

examples = {}
if len(tp_idx) > 0:
    examples['True Positive'] = tp_idx[0]
if len(fn_idx) > 0:
    examples['False Negative'] = fn_idx[0]
if len(tn_idx) > 0:
    examples['True Negative'] = tn_idx[0]

# == Explain each example with its individual SHAP values =======================
test_df_reset = X_test.reset_index(drop=True)
for label, idx in examples.items():
    x_single = X_test_enc[idx:idx + 1]
    sv_single = explainer.shap_values(x_single)
    sv_single = sv_single[1][0] if isinstance(sv_single, list) else np.array(sv_single).reshape(-1)

    pred_prob = shap_model.predict_proba(x_single)[0][1]
    print('=' * 60)
    print(label)
    print(f'Crop: {test_df_reset.iloc[idx]["crop"]}, State: {test_df_reset.iloc[idx]["state"]}, '
          f'Season: {test_df_reset.iloc[idx]["season"]}')
    print(f'Actual: {"At Risk" if y_test.values[idx] == 1 else "Normal/Good"}')
    print(f'Predicted probability of risk: {pred_prob:.3f}')

    contrib = pd.Series(sv_single, index=feature_names_enc).sort_values(key=np.abs, ascending=False).head(5)
    print('Top contributing factors (positive = pushes toward "At Risk"):')
    print(contrib.round(3))
print('=' * 60)

"""### 4.4 — Domain Interpretation of SHAP Results

> The SHAP summary plot and the auto-generated interpretation above show which
factors this run's model relied on most. In general, we'd expect a mix of `crop`
and `season` (since baseline risk differs a lot just by what's being grown and
when), alongside weather variables like rainfall and temperature (since extreme
values in either direction are plausible drivers of a poor season), and possibly
state/soil variables (reflecting the state-level aggregation limitation discussed
below). The **local explanations** in 4.3 matter just as much as the global ones —
they let us sanity-check *individual* predictions, and the **False Negative**
example in particular is worth a close look: that's the exact kind of mistake with
the highest real-world cost, discussed next.

### 4.5 — Ethics Statement

#### Bias & Fairness
- **Geographic/state-level bias:** Soil and weather values are single averages per
  state, so the model cannot distinguish a struggling farm from a thriving one in
  the same state — it can only reflect state-level patterns, not individual farm
  conditions.
- **Crop representation bias:** Common crops (rice, maize, major pulses) have far
  more historical records than rare ones (see Q2 EDA), so the model has had more
  opportunity to learn reliable patterns for common crops and is likely less
  trustworthy for rarely-grown ones.
- **Historical bias:** Training data spans 1997–2020; farming practices and climate
  patterns have shifted since, and will keep shifting, so older relationships may
  not hold as strongly going forward.

#### Privacy
The dataset is entirely state/crop/season/year-level aggregate government-style
statistics — there is no individual farmer or household identifying information
anywhere in it, so this project does not raise personal-data privacy concerns.

#### Uncertainty
None of these models output a calibrated confidence interval by default — the
predicted probability (e.g. 0.73) reflects the model's relative confidence but
should not be read as a precise, guaranteed likelihood. Users should treat
predictions near the 0.5 boundary as genuinely uncertain, not as a confident call
either way.

#### False-Positive vs. False-Negative Costs — and Why Recall Matters Most Here
- A **false negative** (the model says "normal/good" but the season is actually
  low-yield) means a farmer or extension worker gets **no warning at all** before a
  potentially damaging season — the costliest outcome, since it's the exact
  situation this tool exists to prevent.
- A **false positive** (the model flags "at risk" but the season turns out fine)
  costs comparatively little — perhaps some wasted attention from an extension
  worker, or a farmer being more cautious than strictly necessary.
- Because false negatives are far more costly than false positives here, **recall on
  the at-risk class should be weighted more heavily than precision** when deciding
  which model (or which probability threshold) to actually deploy — worth revisiting
  the confusion matrices in Q3.6 with this asymmetry specifically in mind.

#### Human Oversight & Limits on Deployment
- This tool should **flag** possible risk for a human (an extension worker, an
  agricultural officer) to review — not autonomously trigger any action.
- Predictions reflect **historical, state-level, backward-looking patterns**; they
  are not a real-time forecast and should not be treated as one.
- Before any real deployment, performance should be checked **separately per crop
  and per region**, since (as noted above) the model has learned far more from some
  crops/states than others.

---

## Q5 — Live Demo & Prediction Function (2 Marks)

### 5.1 — Save the Trained Pipeline
"""

# == Persist the preprocessing pipeline + best model for reuse ==================
os.makedirs('models', exist_ok=True)
overall_best_name = max(test_results, key=lambda k: test_results[k]['F1'])
overall_best_model = model_map[overall_best_name]

pipeline_artifacts = {
    'preprocessor': preprocessor,
    'model': overall_best_model,
    'model_name': overall_best_name,
    'feature_names': FEATURES,
    'encoded_feature_names': feature_names_enc,
    'cap_bounds': cap_bounds,
    'shap_model': shap_model,
    'shap_model_name': shap_model_name,
}
joblib.dump(pipeline_artifacts, 'models/best_pipeline.joblib')
print(f'Saved pipeline using best model: {overall_best_name}')

"""### 5.2 — Prediction Function with Local Explanation"""

# == predict_and_explain: takes a raw farmer input dict, returns risk + reasons ==
def predict_and_explain(farmer_input, pipeline_path='models/best_pipeline.joblib'):
    """farmer_input must contain: state, crop, season, year, area, fertilizer
    (total), pesticide (total), avg_temp_c, total_rainfall_mm,
    avg_humidity_percent, N, P, K, pH."""
    artifacts = joblib.load(pipeline_path)
    pre = artifacts['preprocessor']
    model = artifacts['model']
    feat_names = artifacts['feature_names']
    caps = artifacts['cap_bounds']

    row = farmer_input.copy()
    row['fertilizer_per_hectare'] = row.pop('fertilizer') / row['area']
    row['pesticide_per_hectare'] = row.pop('pesticide') / row['area']
    for c, upper in caps.items():
        row[c] = min(row[c], upper)

    row_df = pd.DataFrame([row])[feat_names]
    row_enc = pre.transform(row_df)

    risk_prob = model.predict_proba(row_enc)[0][1]
    risk_label = 'AT RISK of low yield' if risk_prob >= 0.5 else 'Normal / Good outlook'

    print(f'Crop: {farmer_input["crop"]} | State: {farmer_input["state"]} | Season: {farmer_input["season"]}')
    print(f'Predicted risk probability: {risk_prob:.1%}')
    print(f'Assessment: {risk_label}')
    return risk_prob, risk_label

"""### 5.3 — Live Demo on Realistic Synthetic Scenarios"""

# == Demo scenario 1: favourable conditions ======================================
scenario_favourable = {
    'state': 'Karnataka', 'crop': 'Rice', 'season': 'Kharif', 'year': 2020,
    'area': 2.0, 'fertilizer': 150.0, 'pesticide': 3.0,
    'avg_temp_c': 27.5, 'total_rainfall_mm': 1100.0, 'avg_humidity_percent': 72.0,
    'N': 72, 'P': 42, 'K': 25, 'pH': 6.9,
}
print('SCENARIO 1 -- Near-normal monsoon rainfall')
predict_and_explain(scenario_favourable)

# == Demo scenario 2: drought-like conditions ====================================
scenario_drought = {
    'state': 'Karnataka', 'crop': 'Rice', 'season': 'Kharif', 'year': 2020,
    'area': 2.0, 'fertilizer': 150.0, 'pesticide': 3.0,
    'avg_temp_c': 30.5, 'total_rainfall_mm': 550.0, 'avg_humidity_percent': 58.0,
    'N': 72, 'P': 42, 'K': 25, 'pH': 6.9,
}
print('SCENARIO 2 -- Same farm, drought-like rainfall and higher temperature')
predict_and_explain(scenario_drought)

# == Demo scenario 3: a different state/crop, for contrast =====================
scenario_other_crop = {
    'state': 'Chhattisgarh', 'crop': 'Maize', 'season': 'Rabi', 'year': 2019,
    'area': 1.5, 'fertilizer': 90.0, 'pesticide': 2.0,
    'avg_temp_c': 24.0, 'total_rainfall_mm': 300.0, 'avg_humidity_percent': 55.0,
    'N': 70, 'P': 35, 'K': 20, 'pH': 6.5,
}
print('SCENARIO 3 -- Different crop, state and season')
predict_and_explain(scenario_other_crop)

"""> **What this demonstrates:** The same farm/crop combination gets a
noticeably different risk assessment when we lower rainfall and raise temperature
(Scenario 1 vs. 2) — a concrete, farmer-relevant example of the kind of "what if the
monsoon is weak this year" question this tool is meant to support. As emphasized
throughout, this is **decision support, not a guaranteed forecast** — it reflects
patterns in 1997–2020 historical data, not a certified prediction for any specific
future season.

---

## 🎥 Section — Three-Minute Pitch & Demo Video Script (for Q5 submission)

This notebook doesn't produce the required video itself, but here's a timing guide
mapped to the cells above so recording it is straightforward:

| Time | What to show | Where in this notebook |
|---|---|---|
| **0:00–0:35** | State the problem (low-yield risk), beneficiaries (farmers, extension workers), and the prediction target. | Q1 |
| **0:35–1:15** | Show the data cleaning (whitespace fix, merge validation), the class-imbalance chart, and 1-2 EDA plots. | Q2.2 – Q2.5 |
| **1:15–2:10** | Show the Q3.6 results table, confusion matrices, and ROC curves — narrate baseline vs. bagging vs. boosting vs. stacking/voting. | Q3.6 |
| **2:10–3:00** | Run one live `predict_and_explain(...)` call on a synthetic farmer scenario, show its top SHAP factors, then briefly state one ethics/limitation point (e.g. state-level data, false-negative cost). | Q4.3, Q4.5, Q5.3 |

---

## ✅ Summary

This notebook builds a leakage-safe, explainable classifier that flags **low-yield
risk** (bottom 20% of yield, per crop) from pre-harvest information — weather, soil,
season, and planned farming inputs — using real crop/soil/weather records for 30
Indian states from 1997–2020.

We audited and handled missing values, duplicates, invalid text formatting,
outliers, categorical encoding, numerical scaling, and class imbalance (Q2); trained
and compared a Decision Tree baseline against Random Forest (bagging), XGBoost and
LightGBM (boosting), and both Voting and Stacking ensembles on an untouched test set
using Accuracy, Precision, Recall, F1, ROC-AUC, and confusion matrices (Q3);
explained the best model both globally and on individual predictions with SHAP, and
discussed bias, privacy, uncertainty, and false-positive/false-negative costs (Q4);
and demonstrated the trained pipeline on realistic synthetic farmer scenarios with a
reusable `predict_and_explain()` function (Q5).

As stressed throughout, this is a **decision-support tool**, not a replacement for
agricultural expertise — its state-level data, historical training window, and
missing farm-level detail (irrigation, crop variety, real-time weather) are real
limitations that should be communicated alongside any prediction it produces.
"""